INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(1, 'student1@email.com','1234','student1', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(2, 'student2@email.com','1234','student2', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(3, 'student3@email.com','1234','student3', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(4, 'student4@email.com','1234','student4', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(5, 'student5@email.com','1234','student5', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(6, 'student6@email.com','1234','student6', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(7, 'student7@email.com','1234','student7', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(8, 'student8@email.com','1234','student8', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(9, 'student9@email.com','1234','student9', 1);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(10, 'student10@email.com','1234','student10', 1);

INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(11, 'professor1@email.com','1234','professor1', 0);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(12, 'professor2@email.com','1234','professor2', 0);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(13, 'professor3@email.com','1234','professor3', 0);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(14, 'professor4@email.com','1234','professor4', 0);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(15, 'professor5@email.com','1234','professor5', 0);
INSERT INTO MEMBER(ID, EMAIL, PASSWORD, NAME, ROLE) VALUES(16, 'professor6@email.com','1234','professor6', 0);

INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(1, '강의1', 'professor1', 0, 10, 1, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(2, '강의2', 'professor1', 1, 11, 2, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(3, '강의3', 'professor2', 0, 10, 3, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(4, '강의4', 'professor3', 0, 10, 4, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(5, '강의5', 'professor4', 0, 10, 5, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(6, '강의6', 'professor5', 0, 10, 4, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(7, '강의7', 'professor6', 0, 10, 3, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(8, '강의8', 'professor6', 1, 11, 2, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(9, '강의9', 'professor6', 2, 12, 1, 3);
INSERT INTO LECTURE(ID, NAME, PROFESSOR, DATE, TIME, STUDENT_LIMIT, CREDIT) VALUES(10, '강의10', 'professor6', 3, 13, 5, 3);